DROP SCHEMA PUBLIC CASCADE;

CREATE TABLE empleados (
    id_empleado INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    dni VARCHAR(15) NOT NULL UNIQUE,
    telefono VARCHAR(20) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    tipo_empleado VARCHAR(20) NOT NULL,
    tipo_detalle VARCHAR(50) NOT NULL,
    salario_anual_bruto DECIMAL(15, 2) NOT NULL,
    CHECK (fecha_nacimiento <= CURRENT_DATE)
);

CREATE TABLE horarios (
    id_horario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empleado INTEGER NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    es_semanal BOOLEAN NOT NULL,
    dia_semana INTEGER, /* Usar valores de 1 (Lunes) a 7 (Domingo) */
    fecha_especifica DATE,
    FOREIGN KEY (id_empleado) REFERENCES empleados(id_empleado)
);
